minetest.register_node("rc_overrides:water_source", {
        description = "Water Source",
        drawtype = "liquid",
        tiles = {
                {
                        name = "default_water_source_animated.png",
                        animation = {
                                type = "vertical_frames",
                                aspect_w = 16,
                                aspect_h = 16,
                                length = 2.0,
                        },
                },
        },
        alpha = 160,
        paramtype = "light",
        walkable = false,
        pointable = false,
        diggable = true,
        buildable_to = true,
        is_ground_content = false,
        drop = "",
        drowning = 1,
        liquidtype = "source",
        liquid_viscosity = 1,
		liquid_alternative_source = "rc_overrides:water_source",
		liquid_alternative_flowing = "rc_overrides:water_source",
		liquid_range = 0,
		liquid_renewable = false,		
		liquids_pointable = true,
        post_effect_color = {a = 103, r = 30, g = 60, b = 90},
        groups = {water = 3, liquid = 3, puts_out_fire = 1},
})

minetest.register_node("rc_overrides:river_water_source", {
        description = "River Water Source",
        drawtype = "liquid",
        tiles = {
                {
                        name = "default_river_water_source_animated.png",
                        animation = {
                                type = "vertical_frames",
                                aspect_w = 16,
                                aspect_h = 16,
                                length = 2.0,
                        },
                },
        },
        alpha = 160,
        paramtype = "light",
        walkable = false,
        pointable = false,
        diggable = true,
        buildable_to = true,
        is_ground_content = false,
        drop = "",
        drowning = 1,
        liquidtype = "source",
        liquid_viscosity = 1,
        liquid_renewable = false,
        liquid_range = 2,
		liquid_alternative_source = "rc_overrides:river_water_source",
		liquid_alternative_flowing = "rc_overrides:river_water_source",
		liquid_range = 0,
		liquid_renewable = false,				
		liquids_pointable = true,		
        post_effect_color = {a = 103, r = 30, g = 76, b = 90},
        groups = {water = 3, liquid = 3, puts_out_fire = 1},
})

minetest.register_node("rc_overrides:lava_source", {
        description = "Lava Source",
        drawtype = "liquid",
        tiles = {
                {
                        name = "default_lava_source_animated.png",
                        animation = {
                                type = "vertical_frames",
                                aspect_w = 16,
                                aspect_h = 16,
                                length = 3.0,
                        },
                },
        },
        paramtype = "light",
        light_source = default.LIGHT_MAX - 1,
        walkable = false,
        pointable = false,
        diggable = true,
        buildable_to = true,
        is_ground_content = false,
        drop = "",
        drowning = 1,
        liquidtype = "source",
        liquid_viscosity = 1,
        liquid_renewable = false,
		liquid_alternative_source = "rc_overrides:lava_source",
		liquid_alternative_flowing = "rc_overrides:lava_source",
		liquid_range = 0,
		liquid_renewable = false,				
		liquids_pointable = true,		
        post_effect_color = {a = 191, r = 255, g = 64, b = 0},
        groups = {lava = 3, liquid = 2, igniter = 1},
})

